/*
 * Copyright 2021 Rigoberto Corporation
 * SPDX-License-Identifier: MIT
 */

const E = 'error';

module.exports = {
	extends: 'eslint:recommended',
	rules: {
		// Possible problems
		'array-callback-return': E,
		'no-await-in-loop': E,
		'no-constructor-return': E,
		'no-duplicate-imports': E,
		'no-promise-executor-return': E,
		'no-self-compare': E,
		'no-template-curly-in-string': E,
		'no-unmodified-loop-condition': E,
		'no-unreachable-loop': E,
		'no-unused-private-class-members': E,
		'no-use-before-define': E,
		'require-atomic-updates': E,

		// Suggestions
		'camelcase': E,
		'capitalized-comments': E,
		'consistent-return': E,
		'consistent-this': E,
		'curly': E,
		'default-param-last': E,
		'dot-notation': E,
		'eqeqeq': [E, 'smart'],
		'grouped-accessor-pairs': E,
		'multiline-comment-style': E,
		'new-cap': E,
		'no-array-constructor': E,
		'no-caller': E,
		'no-eval': E,
		'no-extend-native': E,
		'no-extra-bind': E,
		'no-floating-decimal': E,
		'no-implicit-globals': E,
		'no-implied-eval': E,
		'no-inline-comments': E,
		'no-invalid-this': E,
		'no-iterator': E,
		'no-labels': E,
		'no-lone-blocks': E,
		'no-lonely-if': E,
		'no-loop-func': E,
		'no-multi-str': E,
		'no-nested-ternary': E,
		'no-new': E,
		'no-new-func': E,
		'no-new-object': E,
		'no-new-wrappers': E,
		'no-octal-escape': E,
		'no-proto': E,
		'no-return-assign': E,
		'no-script-url': E,
		'no-sequences': E,
		'no-throw-literal': E,
		'no-undef-init': E,
		'no-undefined': E,
		'no-underscore-dangle': E,
		'no-unneeded-ternary': E,
		'no-unused-expressions': E,
		'no-useless-call': E,
		'no-useless-computed-key': E,
		'no-useless-concat': E,
		'no-useless-return': E,
		'no-var': E,
		'no-void': E,
		'one-var': [E, { initialized: 'never' }],
		'prefer-arrow-callback': E,
		'prefer-const': E,
		'prefer-exponentiation-operator': E,
		'prefer-named-capture-group': E,
		'prefer-numeric-literals': E,
		'prefer-promise-reject-errors': E,
		'prefer-regex-literals': E,
		'prefer-rest-params': E,
		'prefer-spread': E,
		'prefer-template': E,
		'spaced-comment': E,
		'strict': E,
		'symbol-description': E,
		'yoda': E,

		// Layout & Formatting
		'array-bracket-newline': [E, 'consistent'],
		'array-bracket-spacing': E,
		'arrow-spacing': E,
		'block-spacing': E,
		'brace-style': E,
		'comma-dangle': [E, 'only-multiline'],
		'comma-spacing': E,
		'comma-style': E,
		'computed-property-spacing': E,
		'dot-location': [E, 'property'],
		'eol-last': E,
		'func-call-spacing': E,
		'function-paren-newline': E,
		'generator-star-spacing': E,
		'implicit-arrow-linebreak': E,
		'indent': [E, 'tab'],
		'key-spacing': E,
		'keyword-spacing': E,
		'line-comment-position': E,
		'linebreak-style': E,
		'lines-around-comment': [E, { allowBlockStart: true }],
		'lines-between-class-members': E,
		'max-statements-per-line': E,
		'new-parens': E,
		'no-mixed-spaces-and-tabs': [E, 'smart-tabs'],
		'no-multi-spaces': [
			E,
			{
				exceptions: {
					'BinaryExpression': true,
					'VariableDeclarator': true,
				}
			}
		],
		'no-multiple-empty-lines': E,
		'no-trailing-spaces': E,
		'no-whitespace-before-property': E,
		'object-curly-newline': E,
		'object-curly-spacing': [E, 'always'],
		'operator-linebreak': E,
		'quotes': [E, 'single', { avoidEscape: true }],
		'rest-spread-spacing': E,
		'semi': E,
		'semi-spacing': E,
		'semi-style': E,
		'space-before-blocks': E,
		'space-before-function-paren': [E, 'never'],
		'space-in-parens': E,
		'space-infix-ops': E,
		'space-unary-ops': E,
		'switch-colon-spacing': E,
		'template-curly-spacing': E,
		'template-tag-spacing': E,
		'unicode-bom': E,
		'wrap-iife': [E, 'inside'],
		'yield-star-spacing': E,
	}
};
